package com.fourfaith.statisticAnalysis.service;

import com.fourfaith.statisticAnalysis.model.IndustrialDevice;
import com.fourfaith.statisticAnalysis.model.IndustrialDeviceExvoit;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface IndustrialdeviceService {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industrialdevice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industrialdevice
     *
     * @mbggenerated
     */
    int insert(IndustrialDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industrialdevice
     *
     * @mbggenerated
     */
    int insertSelective(IndustrialDevice record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industrialdevice
     *
     * @mbggenerated
     */
    List<IndustrialDevice> selectByPrimaryKey(Map<String,Object> pageInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industrialdevice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IndustrialDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industrialdevice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IndustrialDevice record);

    int updateByKeyName(String deviceName, String ids);

    int updateByKeyNameState(String state,String devicePort);

    List<IndustrialDevice> selectHistoryList(Map<String,Object> pageInfo);

    List<IndustrialDeviceExvoit> selectHistoryListExcel(Map<String,Object> pageInfo);

    IndustrialDevice findWaterTotal(Map<String,Object> pageInfo);
}
